apiVersion: v1
kind: ConfigMap
metadata:
  name: saas-config
  namespace: saas
data:
  NODE_ENV: "production"
  PORT: "4000"
  AUTH_REQUIRED: "true"
  AUTH0_BASE_URL: "https://app.vishuaiaas.com"
  AUTH0_ISSUER_BASE_URL: "https://dev-ml4vedo1qk0j5e8c.us.auth0.com"
  AUTH0_AUDIENCE: "https://dev-ml4vedo1qk0j5e8c.us.auth0.com/api/v2/"
  SERVICE_DOMAIN: "vishuaiaas.com"
  USE_GATEWAY_API: "true"
  GATEWAY_NAME: "saas-gateway"
  GATEWAY_NAMESPACE: "gateway"
  ENABLE_GKE_DEPLOY: "true"
  GCP_PROJECT_ID: "saas-main-vishusystems"
  GCP_REGION: "us-west1"
  GKE_CLUSTER_NAME: "vishu-aiaas"
  DEPLOY_WAIT_SECONDS: "180"
  N8N_DB_HOST: "postgres.saas.svc.cluster.local"
  N8N_DB_PORT: "5432"
  N8N_DB_NAME: "n8n"
  N8N_DB_USER: "n8n"
  SERVICE_ACTIVITY_INGEST_BASE_URL: "http://saas-api.saas.svc.cluster.local:4000"
  HEALTHCARE_PROVIDER_NAME: "ABC HealthCare"
  APP_BASE_URL: "https://app.vishuaiaas.com"
  API_BASE_URL: "http://saas-api.saas.svc.cluster.local:4000"
  NEXT_PUBLIC_API_BASE_URL: "https://api.vishuaiaas.com"
