apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saas-ingress
  namespace: saas
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: saas-ingress-ip
    networking.gke.io/managed-certificates: saas-cert
spec:
  ingressClassName: gce
  defaultBackend:
    service:
      name: saas-web
      port:
        number: 3000
  rules:
    - host: app.vishuaiaas.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: saas-web
                port:
                  number: 3000
    - host: api.vishuaiaas.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: saas-api
                port:
                  number: 4000
