apiVersion: v1
kind: Secret
metadata:
  name: saas-secrets
  namespace: saas
type: Opaque
stringData:
  AUTH0_DOMAIN: "dev-ml4vedo1qk0j5e8c.us.auth0.com"
  AUTH0_CLIENT_ID: "yfnj4Tmoy1XHOnlQxW6T4L0bDsNlsqZa"
  AUTH0_CLIENT_SECRET: "T4zImYdtjsPpvt_TTcbGl0IhlcYdlRekW_yj3-YQ5A82v7LrFXabbRO1FZm3uK2g"
  AUTH0_SECRET: "sansecret"
  MONGODB_URI: "mongodb://mongo.saas.svc.cluster.local:27017/saas_main"
  N8N_DB_PASSWORD: "n8n"
  N8N_ENCRYPTION_KEY: "enckey-vishu"
  SERVICE_ACTIVITY_INGEST_KEY: "vishu-ingest-key"
  GCP_SERVICE_ACCOUNT_KEY_JSON: |
    {"type":"service_account","project_id":"saas-main-vishusystems"}
