apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-web
  namespace: saas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saas-web
  template:
    metadata:
      labels:
        app: saas-web
    spec:
      containers:
        - name: web
          image: docker.io/sjmishra1976/saas-web@sha256:8d8f3b8f8c1bf12addb20016189ebdda2a3c640fefd5d18ca35e73b07d9df4e2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "384Mi"
          envFrom:
            - configMapRef:
                name: saas-config
            - secretRef:
                name: saas-secrets
          env:
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: saas-web
  namespace: saas
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: saas-web
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
